import type { Metadata } from "next";
import { UserProvider } from '@auth0/nextjs-auth0/client';
import { ThemeProvider } from '@mui/material/styles';
import CssBaseline from '@mui/material/CssBaseline';
import theme from '@/kit/theme';

export const metadata: Metadata = {
  title: "Nextjs & Mobx & Mui",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <UserProvider>
          <ThemeProvider theme={theme}>
              <CssBaseline />
              <body>{children}</body>
          </ThemeProvider>
      </UserProvider>
    </html>
  );
}
